spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/blood_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# JWT security configurations
bloodsystem.jwt.secret=BloodSystemSecretKeyForJWTTokenMustBeLongEnoughToPreventWeakKeyExceptions2026!
bloodsystem.jwt.expirationMs=86400000
